# Site settings
title: "Vaidehi Singh"
description: "Personal site and CV of Vaidehi Singh."

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: ""


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vaidehi Singh"
resume_title:                   "Content Therapist, Writer, Blogger"
resume_contact_email:           "vaidehi@jeetesolutions.in"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide (Experience is not shown
# because it is the only required section)
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/vaidus"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://facebook.com/vaidus"
  resume_linkedin_url:          "https://in.linkedin.com/in/vaidehisingh"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://vaidusworld.com"

# Design settings
resume_theme:                   default
